### ISSUE TITLE
Updating the readme.md file and providing more details regarding steps to contribution

### ISSUE THREAD

**Issue by YashSachan2** [AyushTripathiIITP/Fake_news_detection#1]
Providing more details to the readme.md file regarding model used and other metrics obtained.
Providing details regarding steps to contribution.
Mentor please assign this issue to me under codepek
@AyushTripathiIITP

**Comment by AyushTripathiIITP** [comment]
go ahead @YashSachan2

**Comment by YashSachan2** [comment]
@AyushTripathiIITP I have made a pr updating the readme file.Please look into it and assign me points under Codepeak-23.

**Comment by YashSachan2** [comment]
#2

**Comment by YashSachan2** [comment]
#2 Updated Readme.md
