### ISSUE TITLE
We can add more models for comparison and hyperparameter tuning

### ISSUE THREAD

**Issue by YashSachan2** [AyushTripathiIITP/Fake_news_detection#3]
We can form comparison among various classification models and then select out the best on to increase accuracy

**Comment by YashSachan2** [comment]
Please assign it to me under Codepeak-23.

**Comment by AyushTripathiIITP** [comment]
@YashSachan2 go ahead

**Comment by YashSachan2** [comment]
@AyushTripathiIITP I have made a pr for this issue.Please assign me the points for this under Codepeak-23.
