### ISSUE TITLE
Fake News Detection Using BERT

### ISSUE THREAD

**Issue by adi271001** [AyushTripathiIITP/Fake_news_detection#5]
A BERT (Bidirectional Encoder Representations from Transformers) model which predicts if news is fake or true , model gave 99.7% accuracy and have plotted graphs to prove it is not under or over fitted @AyushTripathiIITP please assign this to me under CODEPEAK 2023

**Comment by AyushTripathiIITP** [comment]
Go Ahead @adi271001

**Comment by adi271001** [comment]
@AyushTripathiIITP this issue is solved , please do add the codepeaks tag
